### ISSUE TITLE
vpnprocess.py error

### ISSUE THREAD

**Issue by adrelanos** [leapcode/bitmask_client#1020]
Happening on Debian stretch.

```
[2017-02-05 20:43:03] CRITICAL - L#116  : twisted.logger._stdlib:__call__ - Unhandled error in Deferred:

[2017-02-05 20:43:03] CRITICAL - L#116  : twisted.logger._stdlib:__call__ - 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/services/eip/vpnprocess.py", line 979, in pollState
    self.get_state()
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/services/eip/vpnprocess.py", line 718, in get_state
    return self._parse_state_and_notify(self._send_command("state"))
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/services/eip/vpnprocess.py", line 667, in _parse_state_and_notify
    ts, status_step, ok, ip, remote = parts
ValueError: too many values to unpack
```

**Comment by micah** [comment]
Hi Patrick,

We are finishing off a re-work of bitmask, so the older version hasn't
been getting much love... but until that is ready, I believe that the
problem you are experiencing has to do with the openvpn2.4 version that
has migrated to stretch. If you install the previous non-2.4 version of
openvpn from snapshots.debian.org, you can continue to connect until we
get the new version out.

**Comment by goapunk** [comment]
Not very nice but you could change:
`ts, status_step, ok, ip, remote = parts`
to something like 
```
ts = parts[0]
status_step = parts[1]
ok = parts[2]
ip = parts[3]
remote = parts[4]
state = status_step
```
It will connect at least, no idea if there are any other implications though.
