### ISSUE TITLE
pyasn1 version conflict on debian

### ISSUE THREAD

**Issue by whohoho** [leapcode/bitmask_client#1024]
Happens after installing with repository on debian jessie:

#bitmask
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (pyasn1 0.1.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1>=0.1.8'))

**Comment by whohoho** [comment]
fixed with:

pip install --upgrade pyasn1
