### ISSUE TITLE
Bitmask fails to run on recent Debian Buster kernal update

### ISSUE THREAD

**Issue by marxistvegan** [leapcode/bitmask_client#1027]
Hey all, 
I updated my debian instance running buster. Seems that there is an issue after the linux kernal was updated. I am copying the traceback from command line
`bitmask
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 11, in <module>
    load_entry_point('leap.bitmask==0.9.2', 'console_scripts', 'bitmask')()
  File "/home/marxistvegan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/marxistvegan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/home/marxistvegan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/home/marxistvegan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 61, in <module>
    from leap.bitmask.backend_app import run_backend
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend_app.py", line 28, in <module>
    from leap.bitmask.backend.leapbackend import LeapBackend
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/leapbackend.py", line 23, in <module>
    from leap.bitmask.backend import components
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/components.py", line 44, in <module>
    from leap.bitmask import pix
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/pix.py", line 28, in <module>
    from leap.mail.mail import Account
  File "/usr/lib/python2.7/dist-packages/leap/mail/mail.py", line 41, in <module>
    from leap.mail.adaptors.soledad import SoledadMailAdaptor
  File "/usr/lib/python2.7/dist-packages/leap/mail/adaptors/soledad.py", line 33, in <module>
    from leap.mail import walk
  File "/usr/lib/python2.7/dist-packages/leap/mail/walk.py", line 20, in <module>
    from cryptography.hazmat.backends.multibackend import MultiBackend
ImportError: No module named multibackend
`
Things I have tried

Reinstall

Tried version 0.10 and it works but the packaged one does not

**Comment by meskio** [comment]
We have the plan deprecate the current 0.9.* clients. We will build soon:tm: debian packages for 0.10 and make it the default client.

I'm sorry for the problems.

**Comment by marxistvegan** [comment]
ahh ok, then I will close this out as it will be resolved in the 0.10 which I am using at the moment.
