### ISSUE TITLE
Bitmask "No module named multibackend" debian sid

### ISSUE THREAD

**Issue by j0rgeSD** [leapcode/bitmask_client#1029]
:~$ sudo apt install bitmask
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bitmask is already the newest version (0.9.2.1~20170212151537.168+sid).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

:~$ dpkg -l |grep bitmask
ii  bitmask                                      0.9.2.1~20170212151537.168+sid              all          Provides the desktop client for LEAP
ii  xul-ext-bitmask                              0.0.4+0~20150226193253.24+sid~1.gbp3d05c5   all          Automatic configuration for Bitmask encrypted mail accounts

:~$ bitmask --debug
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 11, in <module>
    load_entry_point('leap.bitmask==0.9.2', 'console_scripts', 'bitmask')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 61, in <module>
    from leap.bitmask.backend_app import run_backend
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend_app.py", line 28, in <module>
    from leap.bitmask.backend.leapbackend import LeapBackend
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/leapbackend.py", line 23, in <module>
    from leap.bitmask.backend import components
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/components.py", line 44, in <module>
    from leap.bitmask import pix
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/pix.py", line 28, in <module>
    from leap.mail.mail import Account
  File "/usr/lib/python2.7/dist-packages/leap/mail/mail.py", line 41, in <module>
    from leap.mail.adaptors.soledad import SoledadMailAdaptor
  File "/usr/lib/python2.7/dist-packages/leap/mail/adaptors/soledad.py", line 33, in <module>
    from leap.mail import walk
  File "/usr/lib/python2.7/dist-packages/leap/mail/walk.py", line 20, in <module>
    from cryptography.hazmat.backends.multibackend import MultiBackend
ImportError: No module named multibackend

:~$ uname -a
Linux xxxxxxx 4.11.0-2-amd64 #1 SMP Debian 4.11.11-1 (2017-07-22) x86_64 GNU/Linux

:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid

**Comment by meskio** [comment]
We want to deprecate bitmask 0.9.2, and hopefully we'll do it soon. The new version we are working on (0.10.0) will come with a lot of changes, improvements, and probably new bugs. Sadly we don't have packages for it yet, they will come soon™️.

We did hit this error before, it's related to the new version of cryptography library. It will work if you roll back to a previous version of the package python-cryptography. Or if you use bitmask from the bundle.

@kalikaneko how do you feel to do a point release with the fix for that? Or should go all in to have packages for the 0.10alphas as soon as possible and recomend sid users to use the alpha?

**Comment by fewrawr** [comment]
I don't know if I should post this here or make a new issue(as a Parabola user), but I don't want to repeat the same issue.So I rolled back to the last version of python cryptography that had multibackend according to https://cryptography.io/en/latest/changelog/. It did not function 

> $ bitmask --debug
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3039, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3023, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3052, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=1.9' distribution was not found and is required by pyopenssl
