### ISSUE TITLE
Problem installing on Ubuntu 14.10

### ISSUE THREAD

**Issue by csoghoian** [leapcode/bitmask_client#802]
Problem seen on fresh Ubuntu 14.10 machine, attempting to follow the instructions [online](https://www.bitmask.com/en/install/linux).

The install instructions have two sections for Ubuntu 14.10 - one for Utopic Unicorn and one for Trusty Tahr. I assumed this was a documentation error, and that the first one was in fact the instructions for 14.10 (Utopic).

The last command we are instructed to enter at the command line to install bitmask is:
```apt-get install bitmask leap-keyring```

If I do that, apt returns with the error:
```Unable to locate package leap-keyring```

If, instead, I try to:
```apt-get install bitmask```

I get the following error:

```
root@chris-ThinkCentre-Edge72:~# apt-get install bitmask
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bitmask : Depends: soledad-client (>= 0.6.0) but it is not going to be installed
           Depends: leap-keymanager but it is not installable
           Depends: leap-mail (>= 0.3.9) but it is not installable
           Depends: python-leap-common (>= 0.3.7) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

What do I do? I can't install leap-keymanger or leap-mail, as they're not available from the deb.bitmask.net repository

As you can see below, I did verify that the bitmask package in question is coming from the bitmask.net repository.
```
root@chris-ThinkCentre-Edge72:~# apt-cache show bitmask
Package: bitmask
Version: 0.7.0.1+0~20141226071510.116+utopic~1.gbp77b576
Architecture: all
Maintainer: Ben Carrillo <ben@futeisha.org>
Installed-Size: 1746
Depends: python-psutil, python:any (<< 2.8), python-srp, python-openssl, python-zope.proxy, soledad-client (>= 0.6.0), leap-keymanager, leap-mail (>= 0.3.9), python-keyring (>= 0.9.2), python:any (>= 2.7.5-5~), python-dateutil, python-ipaddr, python-leap-common (>= 0.3.7), python-requests (>= 1.2.3-1), python, python-oauth, python-daemon, python2.7, python-zmq (>= 14.4.1-1.1), python-crypto, python-argparse, python-netifaces, python-xdg, python-jsonschema (>= 0.7.0), python-setuptools, openvpn, python-pyside.qtcore, python-pyside.qtgui, python-pyside.qtsvg, python-twisted-core
Suggests: policykit-1-gnome
Enhances: openvpn
Homepage: https://leap.se
Priority: extra
Section: misc
Filename: pool/main/b/bitmask/bitmask_0.7.0.1+0~20141226071510.116+utopic~1.gbp77b576_all.deb
Size: 351598
SHA256: 9eed08d4a674e927885703f73c72833f56cf845ee0009363657bfe55aebf3938
SHA1: b40b2a9ae47f1cc7f098063455027027373e47b8
MD5sum: aa86750056db23dcc998dbe17d9f94a5
Description: Provides the desktop client for the LEAP Encryption Access Project Platform.
 LEAP (LEAP Encryption Access Project) develops a plan to secure everyday
 communication, breaking down into discrete services.
 .
 The client for the current phase gives support to the EIP Service. The
 Encrypted Internet Proxy) provides circumvention, location anonymization, and
 traffic encryption in a hassle-free, automatically self-configuring fashion,
 and has an enhanced level of security.
Description-md5: c84de63678e9e2c805252133f8982a53

root@chris-ThinkCentre-Edge72:~# apt-cache policy bitmask
bitmask:
  Installed: (none)
  Candidate: 0.7.0.1+0~20141226071510.116+utopic~1.gbp77b576
  Version table:
     0.7.0.1+0~20141226071510.116+utopic~1.gbp77b576 0
        500 http://deb.bitmask.net/debian/ utopic/main amd64 Packages
```

**Comment by elijh** [comment]
I get the same result:

<pre>
bitmask --debug
2015-01-03 03:56:36,462 - DEBUG    - L#51   : leap:create_logger() - Console handler plugged!
2015-01-03 03:56:36,462 - DEBUG    - L#58   : leap:create_logger() - Leap handler plugged!
2015-01-03 03:56:36,463 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-] Log opened.
2015-01-03 03:56:36,468 - DEBUG    - L#72   : leap.bitmask.util.requirement_checker:check_requirements() - Checking requirements...
2015-01-03 03:56:36,469 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - requests>=1.1.0 ... OK
2015-01-03 03:56:36,469 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - srp>=1.0.2 ... OK
2015-01-03 03:56:36,470 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyopenssl ... OK
2015-01-03 03:56:36,470 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-dateutil  #==1.4  # See  https://leap.se/code/issues/6099 ... OK
2015-01-03 03:56:36,471 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - psutil ... OK
2015-01-03 03:56:36,471 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - ipaddr ... OK
2015-01-03 03:56:36,471 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-daemon # this should not be needed for Windows. ... OK
2015-01-03 03:56:36,472 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - keyring ... OK
2015-01-03 03:56:36,472 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - zope.proxy ... OK
2015-01-03 03:56:36,472 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyzmq ... OK
2015-01-03 03:56:36,473 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.common>=0.3.7 ... OK
2015-01-03 03:56:36,474 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.soledad.client>=0.6.0 ... OK
2015-01-03 03:56:36,474 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.keymanager>=0.3.8 ... OK
2015-01-03 03:56:36,475 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.mail>=0.3.9 ... OK
2015-01-03 03:56:36,475 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - oauth ... OK
2015-01-03 03:56:36,476 - DEBUG    - L#102  : leap.bitmask.util.requirement_checker:check_requirements() - Done
2015-01-03 03:56:36,476 - INFO     - L#172  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-01-03 03:56:36,476 - INFO     - L#173  : leap:start_app() - Bitmask version 0.7.0
2015-01-03 03:56:36,477 - INFO     - L#174  : leap:start_app() - leap.mail version 0.3.9
2015-01-03 03:56:36,478 - INFO     - L#175  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-01-03 03:56:36,478 - INFO     - L#177  : leap:start_app() - Starting app
2015-01-03 03:56:36,479 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-] Traceback (most recent call last):
2015-01-03 03:56:36,479 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "/usr/bin/bitmask", line 9, in <module>
2015-01-03 03:56:36,480 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]     load_entry_point('leap.bitmask==0.7.0', 'console_scripts', 'bitmask')()
2015-01-03 03:56:36,480 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 179, in start_app
2015-01-03 03:56:36,480 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]     generate_certificates()
2015-01-03 03:56:36,481 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/utils.py", line 45, in generate_certificates
2015-01-03 03:56:36,481 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]     zmq.auth.create_certificates(KEYS_DIR, "frontend")
2015-01-03 03:56:36,482 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "/usr/lib/python2.7/dist-packages/zmq/auth/certs.py", line 57, in create_certificates
2015-01-03 03:56:36,482 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]     public_key, secret_key = zmq.curve_keypair()
2015-01-03 03:56:36,483 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "utils.pyx", line 60, in zmq.backend.cython.utils.curve_keypair (zmq/backend/cython/utils.c:985)
2015-01-03 03:56:36,483 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]   File "/usr/lib/python2.7/dist-packages/zmq/error.py", line 113, in _check_rc
2015-01-03 03:56:36,483 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-]     raise ZMQError(errno)
2015-01-03 03:56:36,483 - DEBUG    - L#53   : leap:write() - 2015-01-03 03:56:36+0100 [-] zmq.error.ZMQError: Operation not supported
</pre>

<pre>
apt-cache policy python-zmq
python-zmq:
  Installed: 14.4.1-1.1+0~20141111215437.12+utopic~1.gbpc12fc5
  Candidate: 14.4.1-1.1+0~20141111215437.12+utopic~1.gbpc12fc5
  Version table:
 *** 14.4.1-1.1+0~20141111215437.12+utopic~1.gbpc12fc5 0
        500 http://deb.bitmask.net/debian/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status
     14.3.1-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ utopic/universe amd64 Packages
</pre>

**Comment by micah** [comment]
Christopher Soghoian <notifications@github.com> writes:

> Ok. That helped. I was (after an apt-get update) able to install bitmask.
>
> However, it won't start. Trying to run the bitmask client doesn't do anything, or cause any windows to open.
> ```
> chris@chris-ThinkCentre-Edge72:~$ bitmask
> chris@chris-ThinkCentre-Edge72:~$ 
> ```

Thanks, I've fixed that issue, you should be able to resolve it on your
machine by doing:

```
apt-get update
apt-get -u dist-upgrade
```

that should install the missing libsodium13 and libzmq3 packages, and
then bitmask should start properly.

Sorry about this hassle, I normally would have tested this better, but
the timing with the holidays+congress travel screwed me up.

**Comment by csoghoian** [comment]
Hooray. Works beautifully now.

**Comment by zero-1stContact** [comment]
I tried the recommendations above but when i enter "bitmask" in the terminal below is my response...

Traceback (most recent call last):
  File "/usr/bin/bitmask", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (leap.common 0.3.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('leap.common>=0.4.3'))

**Comment by micah** [comment]
Hello,

Unfortunately, we can no longer support Ubuntu LTS with the packages. However, there is a solution. Just remove the package, and then download the bundle, you can find that at https://dl.bitmask.net.
