### ISSUE TITLE
Bitmask doesn't startup

### ISSUE THREAD

**Issue by Mik3r** [leapcode/bitmask_client#895]
I just install it following the commands for Ubuntu 14.04 LTS.  Every time I click on bitmask icon nothing happens.

I run `bitmask --debug` and this is what I get:

```
2015-09-08 19:52:39,615 - DEBUG    - L#51   : leap:create_logger() - Console handler plugged!
2015-09-08 19:52:39,615 - DEBUG    - L#58   : leap:create_logger() - Leap handler plugged!
2015-09-08 19:52:39,616 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-] Log opened.
2015-09-08 19:52:39,630 - DEBUG    - L#72   : leap.bitmask.util.requirement_checker:check_requirements() - Checking requirements...
2015-09-08 19:52:39,632 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - requests>=1.1.0 ... OK
2015-09-08 19:52:39,632 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - srp>=1.0.2 ... OK
2015-09-08 19:52:39,632 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyopenssl ... OK
2015-09-08 19:52:39,632 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-dateutil ... OK
2015-09-08 19:52:39,633 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - psutil ... OK
2015-09-08 19:52:39,633 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - ipaddr ... OK
2015-09-08 19:52:39,633 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-daemon # this should not be needed for Windows. ... OK
2015-09-08 19:52:39,633 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - keyring ... OK
2015-09-08 19:52:39,633 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - zope.proxy ... OK
2015-09-08 19:52:39,634 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyzmq ... OK
2015-09-08 19:52:39,634 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.common>=0.3.7 ... OK
2015-09-08 19:52:39,634 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.soledad.client>=0.6.0 ... OK
2015-09-08 19:52:39,634 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.keymanager>=0.3.8 ... OK
2015-09-08 19:52:39,635 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.mail>=0.3.9 ... OK
2015-09-08 19:52:39,635 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - oauth ... OK
2015-09-08 19:52:39,635 - DEBUG    - L#102  : leap.bitmask.util.requirement_checker:check_requirements() - Done
2015-09-08 19:52:39,635 - INFO     - L#174  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-09-08 19:52:39,635 - INFO     - L#175  : leap:start_app() - Bitmask version 0.8.1
2015-09-08 19:52:39,635 - INFO     - L#176  : leap:start_app() - leap.mail version 0.3.11
2015-09-08 19:52:39,636 - INFO     - L#177  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-09-08 19:52:39,636 - INFO     - L#179  : leap:start_app() - Starting app
2015-09-08 19:52:39,636 - DEBUG    - L#63   : leap.bitmask.backend.backend_proxy:__init__() - Connecting to server...
2015-09-08 19:52:39,637 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-] Traceback (most recent call last):
2015-09-08 19:52:39,638 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "/usr/bin/bitmask", line 9, in <module>
2015-09-08 19:52:39,638 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]     load_entry_point('leap.bitmask==0.8.1', 'console_scripts', 'bitmask')()
2015-09-08 19:52:39,638 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 181, in start_app
2015-09-08 19:52:39,638 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]     backend_running = BackendProxy().check_online()
2015-09-08 19:52:39,639 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend_proxy.py", line 75, in __init__
2015-09-08 19:52:39,639 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]     socket.curve_serverkey = public
2015-09-08 19:52:39,639 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "/usr/lib/python2.7/dist-packages/zmq/sugar/attrsettr.py", line 29, in __setattr__
2015-09-08 19:52:39,640 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]     self._set_attr_opt(upper_key, opt, value)
2015-09-08 19:52:39,640 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "/usr/lib/python2.7/dist-packages/zmq/sugar/attrsettr.py", line 33, in _set_attr_opt
2015-09-08 19:52:39,640 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]     self.set(opt, value)
2015-09-08 19:52:39,640 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-]   File "socket.pyx", line 314, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3278)
2015-09-08 19:52:39,641 - DEBUG    - L#53   : leap:write() - 2015-09-08 19:52:39-0400 [-] TypeError: expected bytes, got: None
```

just to run smoothly

**Comment by Mik3r** [comment]
I disable OpenDNS.  Can I get a hint at least?

**Comment by ivanalejandro0** [comment]
Hello @Mik3r , sorry it took so long to give you a response.
We was focusing on 0.9.0 stable release.
We dropped (temporally) .deb packages support on Ubuntu 14.04 due to difficulties backporting some libraries.
You can use the standalone bundle though.

For more information see https://bitmask.net/en/install/linux.

P.S.: for quicker responses you may want to report issues on https://leap.se/code/projects/report-issues and/or asking on #leap @ freenode.
