### ISSUE TITLE
bug: TypeError in lib/gnupg/_util.py:_match_version_string (Manjaro)

### ISSUE THREAD

**Issue by funkyfuture** [leapcode/bitmask_client#941]
ciao tutti, i'm running on Manjaro, using Bitmask 0.9.1 and this happens upon key generation for mail.
the error is unhandled by the UI, that just hangs.

```
...
[2015-11-06 14:32:04] DEBUG    - L#646  : leap.bitmask.services.soledad.soledadbootstrapper:_success - Soledad has been synced!
[2015-11-06 14:32:04] DEBUG    - L#532  : leap.bitmask.services.soledad.soledadbootstrapper:_gen_key - Retrieving key for user@mail.bitmask.net
[2015-11-06 14:32:04] DEBUG    - L#375  : leap.keymanager:get_key - getting key for user@mail.bitmask.net
[2015-11-06 14:32:04] DEBUG    - L#537  : leap.bitmask.services.soledad.soledadbootstrapper:if_not_found_generate - Key not found. Generating key for user@mail.bitmask.net
[2015-11-06 14:32:04] ERROR    - L#550  : leap.bitmask.services.soledad.soledadbootstrapper:log_err - Error while %s key!
[2015-11-06 14:32:04] ERROR    - L#551  : leap.bitmask.services.soledad.soledadbootstrapper:log_err - int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File ".../bin/Bitmask-linux64-0.9.1/./lib/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File ".../bin/Bitmask-linux64-0.9.1/./lib/leap/keymanager/openpgp.py", line 257, in _gen_key
    with TempGPGWrapper(gpgbinary=self._gpgbinary) as gpg:
  File ".../bin/Bitmask-linux64-0.9.1/./lib/leap/keymanager/openpgp.py", line 92, in __enter__
    self._build_keyring()
  File ".../bin/Bitmask-linux64-0.9.1/./lib/leap/keymanager/openpgp.py", line 124, in _build_keyring
    homedir=tempfile.mkdtemp())
  File ".../bin/Bitmask-linux64-0.9.1/./lib/gnupg/gnupg.py", line 162, in __init__
    self.create_trustdb()
  File ".../bin/Bitmask-linux64-0.9.1/./lib/gnupg/gnupg.py", line 172, in create_trustdb
    if self.is_gpg2():
  File ".../bin/Bitmask-linux64-0.9.1/./lib/gnupg/gnupg.py", line 212, in is_gpg2
    return _util._is_gpg2(self.binary_version)
  File ".../bin/Bitmask-linux64-0.9.1/./lib/gnupg/_util.py", line 529, in _is_gpg2
    (major, minor, micro) = _match_version_string(version)
  File ".../bin/Bitmask-linux64-0.9.1/./lib/gnupg/_util.py", line 607, in _match_version_string
    major, minor, micro = int(g[0]), int(g[2]), int(g[4])
TypeError: int() argument must be a string or a number, not 'NoneType'
[2015-11-06 14:36:04] INFO     - L#109  : twisted.logger._stdlib:__call__ - Stopping factory <leap.common.http._HTTP11ClientFactory instance at 0x7feccc25c5f0>
```

**Comment by micah** [comment]
Frank Sachsenheim <notifications@github.com> writes:

> ciao tutti, i'm running on Manjaro, using Bitmask 0.9.1 and this happens upon key generation for mail.
> the error is unhandled by the UI, that just hangs.

How did you install bitmask?

And what kind of distribution is Manjaro? Is it based or derived from
Debian or something?

**Comment by funkyfuture** [comment]
[Manjaro](https://manjaro.github.io/) is an Arch-based distro.

i'm using [the bundled tar-ball](https://dl.bitmask.net/client/linux/stable/Bitmask-linux64-latest.tar.bz2) and provided a patch to solve the issue (see reference above).

however, [i can't test further](https://github.com/leapcode/bitmask_client/issues/944) after incorporating that fix. :-(

**Comment by ivanalejandro0** [comment]
Can you tell the `gpg` version that you're using?
You can paste the `gpg --version`  output in here.

It may be that this is related with #946

**Comment by funkyfuture** [comment]
it's gpg 2.1.9 with libgcrypt 1.6.4

however, #946 happens when i applied [this patch](https://github.com/leapcode/python_gnupg-ng/issues/4).

**Comment by funkyfuture** [comment]
closing this as there's a package in the AUR now (though its installation fails)
