### ISSUE TITLE
bug: gpg runs idle (Ubuntu Wily)

### ISSUE THREAD

**Issue by funkyfuture** [leapcode/bitmask_client#950]
here's my attempt to run bitmask on a fresh Ubuntu Wily with an installation from the repositories.
a `gpg` process is spawned, but it hardly consumes any cpu usage for more than two hours.

the same behaviour is exposed when running bitmask from the bundle with its contributed gpg-binary.

that are the arguments the gpg-process got:
`--no-options --no-emit-version --no-tty --status-fd 2 --homedir /tmp/tmpMeGV6b --no-default-keyring --keyring /tmp/tmpMeGV6b/pubring.gpg --secret-keyring /tmp/tmpMeGV6b/secring.gpg --no-use-agent --batch --gen-key`

```
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Checking requirements...
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - requests>=1.1.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - srp>=1.0.2 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - pyopenssl ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - psutil ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - ipaddr ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - python-daemon # this should not be needed for Windows. ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - keyring ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - zope.proxy ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - pyzmq ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - txzmq ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - oauth ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - logbook>=0.7.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - leap.soledad.client>=0.6.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - leap.keymanager>=0.4.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - leap.mail>=0.4.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - leap.common>=0.4.0 ... OK
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Done
[2015-11-10 00:56:45] INFO     - L#None : None:None - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2015-11-10 00:56:45] INFO     - L#None : None:None - Bitmask version 0.9.1
[2015-11-10 00:56:45] INFO     - L#None : None:None - leap.mail version 0.4.0
[2015-11-10 00:56:45] INFO     - L#None : None:None - LSB Release info:
[2015-11-10 00:56:45] INFO     - L#None : None:None - Distributor ID:	Ubuntu
[2015-11-10 00:56:45] INFO     - L#None : None:None - Description:	Ubuntu 15.10
[2015-11-10 00:56:45] INFO     - L#None : None:None - Release:	15.10
[2015-11-10 00:56:45] INFO     - L#None : None:None - Codename:	wily
[2015-11-10 00:56:45] INFO     - L#None : None:None - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2015-11-10 00:56:45] INFO     - L#None : None:None - Starting app
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Setting up ZMQ connection to server...
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Checking whether backend is online...
[2015-11-10 00:56:45] WARNING  - L#None : None:None - Backend is offline!
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Backend online: False
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Connecting to signaling server...
[2015-11-10 00:56:45] DEBUG    - L#None : None:None - Starting Twisted reactor.
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Setting up ZMQ connection to server...
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Starting backend proxy...
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Checking whether backend is online...
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Starting ZMQ loop.
[2015-11-10 00:56:46] WARNING  - L#None : None:None - Backend is offline!
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Running SignalerQt loop
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:46] DEBUG    - L#None : None:None - Running initializer for Linux
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - eip machine started
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Starting mail state machine...
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Selected keyring: <class 'keyring.backends.SecretService.Keyring'>
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - State Encrypted Internet::off entered. Emitting signal ...
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - State Mail::off entered. Emitting signal ...
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - State IMAP::off entered. Emitting signal ...
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - State IMAP::off entered. Emitting signal ...
[2015-11-10 00:56:47] WARNING  - L#None : None:None - Trying to update eip enabled status but there's no default provider. Disabling EIP for the time being...
[2015-11-10 00:56:47] INFO     - L#109  : twisted.logger._stdlib:__call__ - Setting up provider mail.bitmask.net...
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Checking name resolution for u'mail.bitmask.net'
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Checking https for u'mail.bitmask.net'
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Hiding EIP start button
[2015-11-10 00:56:47] DEBUG    - L#None : None:None - Disabled
[2015-11-10 00:56:49] DEBUG    - L#None : None:None - Downloading provider info for u'mail.bitmask.net'
[2015-11-10 00:56:49] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:49] DEBUG    - L#None : None:None - Requesting for provider.json... uri: https://api.mail.bitmask.net:4430/provider.json, verify: /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem, headers: {'if-modified-since': 'Mon Oct  5 06:39:55 2015 GMT'}
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Request status code: 200
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Provider definition has been modified
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Downloading ca cert for u'mail.bitmask.net' at u'https://mail.bitmask.net/ca.crt'
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Checking ca fingerprint for u'mail.bitmask.net' and cert '/home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem'
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Checking api certificate for https://api.mail.bitmask.net:4430 and cert /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Authentication preprocessing...
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Starting authentication process...
[2015-11-10 00:56:51] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:54] DEBUG    - L#None : None:None - Processing challenge...
[2015-11-10 00:56:54] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Verifying session...
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Session verified.
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - SUCCESS LOGIN
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Successful login!
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Hiding EIP start button
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Disabled
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Downloading Soledad config for mail.bitmask.net
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Downloading SOLEDAD config from: https://api.mail.bitmask.net:4430/1/config/soledad-service.json
[2015-11-10 00:56:55] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - SOLEDAD definition has not been modified
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - secrets_path:/home/user/.config/leap/soledad/cb034a99c31d7b65a7c1456e44a36894.secret
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - local_db:/home/user/.config/leap/soledad/cb034a99c31d7b65a7c1456e44a36894.db
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - Using soledad server url: https://antelope.mail.bitmask.net:2323/user-cb034a99c31d7b65a7c1456e44a36894
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:57] DEBUG    - L#None : None:None - Trying to init soledad....
[2015-11-10 00:56:57] INFO     - L#248  : leap.soledad.client.secrets:_has_secret - Checking if there's a secret in local storage...
[2015-11-10 00:56:57] INFO     - L#258  : leap.soledad.client.secrets:_has_secret - Found a secret in local storage.
[2015-11-10 00:56:58] DEBUG    - L#188  : leap.soledad.client.encdecpool:start - Starting the encryption loop...
[2015-11-10 00:56:58] DEBUG    - L#365  : leap.soledad.client.pragmas:set_write_ahead_logging - SQLCIPHER: SETTING WRITE-AHEAD LOGGING
[2015-11-10 00:56:58] DEBUG    - L#332  : leap.soledad.client.pragmas:set_synchronous_normal - SQLCIPHER: SETTING SYNCHRONOUS NORMAL
[2015-11-10 00:56:58] DEBUG    - L#346  : leap.soledad.client.sqlcipher:close - SQLCipher backend: closing
[2015-11-10 00:56:58] DEBUG    - L#365  : leap.soledad.client.pragmas:set_write_ahead_logging - SQLCIPHER: SETTING WRITE-AHEAD LOGGING
[2015-11-10 00:56:58] DEBUG    - L#332  : leap.soledad.client.pragmas:set_synchronous_normal - SQLCIPHER: SETTING SYNCHRONOUS NORMAL
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - Soledad has been initialized.
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - initializing keymanager...
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - Going to verify SSL against /home/user/.config/leap/providers/mail.bitmask.net/keys/ca/cacert.pem
[2015-11-10 00:56:58] DEBUG    - L#365  : leap.soledad.client.pragmas:set_write_ahead_logging - SQLCIPHER: SETTING WRITE-AHEAD LOGGING
[2015-11-10 00:56:58] DEBUG    - L#332  : leap.soledad.client.pragmas:set_synchronous_normal - SQLCIPHER: SETTING SYNCHRONOUS NORMAL
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - Trying to send key to server...
[2015-11-10 00:56:58] DEBUG    - L#375  : leap.keymanager:get_key - getting key for user@mail.bitmask.net
[2015-11-10 00:56:58] DEBUG    - L#365  : leap.soledad.client.pragmas:set_write_ahead_logging - SQLCIPHER: SETTING WRITE-AHEAD LOGGING
[2015-11-10 00:56:58] DEBUG    - L#332  : leap.soledad.client.pragmas:set_synchronous_normal - SQLCIPHER: SETTING SYNCHRONOUS NORMAL
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - No key found for user@mail.bitmask.net, it might be because soledad not synced yet or it will generate it soon.
[2015-11-10 00:56:58] DEBUG    - L#None : None:None - BOOTSTRAPPER: trying to sync Soledad....
[2015-11-10 00:56:58] INFO     - L#109  : twisted.logger._stdlib:__call__ - Starting factory <leap.common.http._HTTP11ClientFactory instance at 0x7f80d5f98ea8>
[2015-11-10 00:57:01] DEBUG    - L#78   : leap.soledad.client.sync:sync - Database isn't ready on server. Will be created.
[2015-11-10 00:57:01] DEBUG    - L#79   : leap.soledad.client.sync:sync - Reason: <class 'u1db.errors.DatabaseDoesNotExist'>
[2015-11-10 00:57:01] DEBUG    - L#93   : leap.soledad.client.sync:sync - Soledad target sync info:
  target replica uid: None
  target generation: 0
  target trans id: 
  target my gen: 0
  target my trans_id: 
  source replica_uid: 2fb3aced3f5a44e1b189f099a412d8fa

[2015-11-10 00:57:01] DEBUG    - L#112  : leap.soledad.client.sync:sync - Soledad sync: there are 0 documents to send.
[2015-11-10 00:57:01] DEBUG    - L#125  : leap.soledad.client.sync:sync - Soledad source sync info:
  last target gen known to source: 0
  last target trans_id known to source: 
[2015-11-10 00:57:01] DEBUG    - L#None : None:None - Soledad has been synced!
[2015-11-10 00:57:01] DEBUG    - L#None : None:None - Retrieving key for user@mail.bitmask.net
[2015-11-10 00:57:01] DEBUG    - L#375  : leap.keymanager:get_key - getting key for user@mail.bitmask.net
[2015-11-10 00:57:01] DEBUG    - L#365  : leap.soledad.client.pragmas:set_write_ahead_logging - SQLCIPHER: SETTING WRITE-AHEAD LOGGING
[2015-11-10 00:57:01] DEBUG    - L#332  : leap.soledad.client.pragmas:set_synchronous_normal - SQLCIPHER: SETTING SYNCHRONOUS NORMAL
[2015-11-10 00:57:01] DEBUG    - L#None : None:None - Key not found. Generating key for user@mail.bitmask.net
[2015-11-10 00:57:01] INFO     - L#265  : leap.keymanager.openpgp:_gen_key - About to generate keys... This might take SOME time.
^C[2015-11-10 02:10:37] DEBUG    - L#None : None:None - MainProcess: SIGNAL #2 catched.
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Quitting...
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Stopping services...
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Stopping mail services
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Mail services not started.
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Doing logout
[2015-11-10 02:10:37] DEBUG    - L#None : None:None - Terminating vpn
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - Final quit...
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - Closing soledad...
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - SignalerQt thread stopped.
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - Finished ZMQ loop.
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - BackendProxy worker stopped.
[2015-11-10 02:10:40] DEBUG    - L#None : None:None - Cleaning pidfiles
Killing all the children processes...
[2015-11-10 02:10:40] INFO     - L#109  : twisted.logger._stdlib:__call__ - Received SIGTERM, shutting down.
[2015-11-10 02:10:40] INFO     - L#109  : twisted.logger._stdlib:__call__ - Received SIGTERM, shutting down.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logbook/handlers.py", line 214, in handle
    self.emit(record)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/logs/safezmqhandler.py", line 118, in emit
    socket.send(json.dumps(self.export_record(record)).encode("utf-8"))
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
  File "zmq/backend/cython/socket.pyx", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)
  File "zmq/backend/cython/socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)
  File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6248)
    raise ZMQError(errno)
ZMQError: Interrupted system call
Logged from file /usr/lib/python2.7/dist-packages/twisted/logger/_stdlib.py, line 109
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logbook/handlers.py", line 214, in handle
    self.emit(record)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/logs/safezmqhandler.py", line 118, in emit
    socket.send(json.dumps(self.export_record(record)).encode("utf-8"))
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
  File "zmq/backend/cython/socket.pyx", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)
  File "zmq/backend/cython/socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)
  File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6248)
    raise ZMQError(errno)
ZMQError: Interrupted system call
Logged from file /usr/lib/python2.7/dist-packages/twisted/logger/_stdlib.py, line 109
[2015-11-10 02:10:40] INFO     - L#109  : twisted.logger._stdlib:__call__ - Received SIGTERM, shutting down.
[2015-11-10 02:10:40] INFO     - L#269  : leap.keymanager.openpgp:_gen_key - Keys for user@mail.bitmask.net have been successfully generated.
[2015-11-10 02:10:41] ERROR    - L#39   : leap.common.check:leap_assert - Bug: Keyring has wrong number of keys: 0.
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/bin/bitmask", line 9, in <module>
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     load_entry_point('leap.bitmask==0.9.1', 'console_scripts', 'bitmask')()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 232, in start_app
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     backend_process.start()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self._popen = Popen(self)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     code = process_obj._bootstrap()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self.run()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self._target(*self._args, **self._kwargs)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 226, in <lambda>
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     backend = lambda: run_backend(opts.danger, flags_dict, frontend_pid)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend_app.py", line 94, in run_backend
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     backend.run()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend.py", line 173, in run
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     reactor.run()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self.mainLoop()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self.runUntilCurrent()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     f(*a, **kw)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self._startRunCallbacks(result)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     self._runCallbacks()
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     current.result = callback(current.result, *args, **kw)
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -   File "/usr/lib/python2.7/dist-packages/leap/keymanager/openpgp.py", line 275, in _gen_key
[2015-11-10 02:10:41] ERROR    - L#45   : leap.common.check:leap_assert -     'Keyring has wrong number of keys: %d.' % len(pubkeys))
[2015-11-10 02:10:41] ERROR    - L#None : None:None - Error while %s key!
[2015-11-10 02:10:41] ERROR    - L#None : None:None - Keyring has wrong number of keys: 0.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/leap/keymanager/openpgp.py", line 275, in _gen_key
    'Keyring has wrong number of keys: %d.' % len(pubkeys))
  File "/usr/lib/python2.7/dist-packages/leap/common/check.py", line 48, in leap_assert
    assert condition, message
AssertionError: Keyring has wrong number of keys: 0.
[2015-11-10 02:10:41] INFO     - L#109  : twisted.logger._stdlib:__call__ - Stopping factory <leap.common.http._HTTP11ClientFactory instance at 0x7f80d5f98ea8>
[2015-11-10 02:10:41] DEBUG    - L#346  : leap.soledad.client.sqlcipher:close - SQLCipher backend: closing
[2015-11-10 02:10:41] DEBUG    - L#346  : leap.soledad.client.sqlcipher:close - SQLCipher backend: closing
[2015-11-10 02:10:41] DEBUG    - L#346  : leap.soledad.client.sqlcipher:close - SQLCipher backend: closing
[2015-11-10 02:10:41] INFO     - L#109  : twisted.logger._stdlib:__call__ - Main loop terminated.
[2015-11-10 02:10:41] DEBUG    - L#None : None:None - Finished Twisted reactor.
```

**Comment by meskio** [comment]
This error looks similar to  #946

**Comment by funkyfuture** [comment]
nope, here the gpg-process is spawned and runs idle. in #946 it isn't spawned at all.
notice the timestamps.

**Comment by funkyfuture** [comment]
closing as Wily isn't supported anymore.
