### ISSUE TITLE
Can't run Bitmask from repo on Ubuntu 16.04

### ISSUE THREAD

**Issue by bungabunga** [leapcode/bitmask_client#999]
There's no way for me to run Bitmask from repository on Ubuntu 16.04:

- if i install it via Wily (15.10) repo it doesn't start.
`bitmask
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:187: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 9, in <module>
    load_entry_point('leap.bitmask==0.9.1', 'console_scripts', 'bitmask')()
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 218, in start_app
    backend_running = BackendProxy().check_online()
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend_proxy.py", line 153, in __init__
    self._connection = ZmqREQConnection(self.SERVER, self._set_online)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend_proxy.py", line 71, in __init__
    self._init_zmq()
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend_proxy.py", line 93, in _init_zmq
    public, _ = get_backend_certificates()
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/utils.py", line 123, in get_backend_certificates
    public, secret = zmq.auth.load_certificate(backend_secret_file)
  File "/usr/lib/python2.7/dist-packages/zmq/auth/certs.py", line 106, in load_certificate
    raise ValueError("No public key found in %s" % filename)
ValueError: No public key found in /home/jst/.config/leap/zmq_certificates/backend.key_secret
Killing all the children processes...`

- if i change Wily repo with Xenial (16.04) it doesn't wan't to install.
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 bitmask : Depends: leap-mail (>= 0.4.1) but it is not going to be installed
           Depends: python-leap-common (>= 0.5.1) but 0.4.11.1+0~20151102160716.36+vivid~1.gbpe074ea is to be installed
           Depends: soledad-client (>= 0.8.0) but it is not going to be installed
           Recommends: xul-ext-bitmask but it is not installable
E: Unable to correct problems, you have held broken packages.`

The only way for me to run it atm is via Ubuntu bundle.

**Comment by bungabunga** [comment]
solved!
